### PR TITLE
ENH: New UI views for "Most Liked" and "Most Replies"

### LINKED ISSUE #420: ENH: New Default filters for quick access
I've been using the Forums module for quite some time now and I believe that including a couple more filters at the top of the module will help reduce time searching. My suggestions are the following:

1. Top 10 messages or replies with most reactions (the "Thumbs up") labeled as "Most Popular Replies"
2. Top 10 subjects with high amount of responses labeled as "Hot Topics"

I visualize these new default filters right next to "Not Read" and ""Unanswered" at the top of the module.

"Most Popular Replies" could help users find the answers from the community with highest thumbs up which could means that those answers are the fix for a top issue everybody is asking; also, this will encourage people to use the "Thumbs up" button.

"Hot Topics" could help users to find the most active conversations right now and allow community members to jump into a conversation where everybody is helping out.

P.D. This is my first Issue on GitHub so I apologize in advanced for any mistake or missing information. :-)

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Adds new views for topics that are most liked and have most replies.
image
image

## Changes made
- new stored procedures
- new UI views / text resources

## How did you test these updates?  
manually installed new stored procedures, built test 08.00.00 version, and tested against sanitized copy of dnncommunity.org

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #420

### CODE REVIEW

**Comment by johnhenley** [comment]
@WillStrohl pulled forward to 08.00.00

**Comment by WillStrohl** [comment]
@johnhenley When I get to this one, I can see there are already conflicts, including your buddy, `SqlDataProvider`.  😜

**Comment by johnhenley** [comment]
> @johnhenley When I get to this one, I can see there are already conflicts, including your buddy, `SqlDataProvider`. 😜

@WillStrohl  hopefully this one will not have a conflict anymore

**Comment by Timo-Breumelhof** [comment]
@johnhenley we now have a conflict with my updated module.css Can you pull the dev version in and re-commit?
(or maybe you have a better idea..?)

**Comment by johnhenley** [comment]
> @johnhenley we now have a conflict with my updated module.css Can you pull the dev version in and re-commit? (or maybe you have a better idea..?)

done. this is normal game I play with Will a lot :)

**Comment by Timo-Breumelhof** [comment]
@johnhenley glad we can play that game too now.. ;-)

**Pull request merged**
