### PR TITLE
Load FontAwesome locally rather than from CDN

### LINKED ISSUE #556: ENH: Install and load FontAwesome locally rather than from CDN
## Is your feature request related to a problem?
Some installations have DNN installed in an intranet and may not have internet access to the CDN from which FontAwesome is currently loaded. 
## Describe the solution you'd like
Include FontAwesome in the install package and load it locally.

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Load FontAwesome font resources locally rather than from CDN.

## Changes made
- Add FontAwesome 4.7 to project
- Load CSS using DNN Client Resource Manager

## How did you test these updates?  

Local install

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #556

### CODE REVIEW

**Comment by johnhenley** [comment]
@Timo-Breumelhof  to review MimeType issue in web.config for woff2 fonts.

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Comment by johnhenley** [comment]
@Timo-Breumelhof reminder to look at woff2 mime type issue. Not specific for Forums, but also affects skins and floods the admin logs....
image

**Comment by johnhenley** [comment]
> @Timo-Breumelhof  to review MimeType issue in web.config for woff2 fonts.
> 
> image
> 
> 

@Timo

**Pull request merged**
