### PR TITLE
Save DateTimes as UTC / Display based on User Preferences TimeZone

### LINKED ISSUE #86: Save Dates as UTC instead of server time
## Describe the bug
The Module saves dates in the Current servers timezone and not in UTC
IMO that's risky, in case of server reconfiguration or if someone would move the installation to a server in another time zone.
Related: https://github.com/DNNCommunity/Dnn.CommunityForums/issues/83

Although quite a bit of work (needs upgrade script for existing sites), it would make the module more robust IMO

## Software Versions
- DNN: 09.09.00
- Module: 06.05.01

### PR DESCRIPTION
**Pull request by johnhenley**
## Changes made
- All AF tables now store datetime fields as UTC rather than database server datetime
- Dates/Times are displayed using user's preferred time zone
- Existing datetime data is converted during module installation

## Conversion Notes

- During installation of this update, existing data will be converted using the time zone difference between the database server's time zone and UTC.

- In addition, if your DNN portal is set to one of these US or EU time zones, the conversion honors daylight savings time (DST) during the conversion:

1. 'Eastern Standard Time'
2. 'Central Standard Time'
3. 'Mountain Standard Time' 
4. 'Pacific Standard Time' 
5. 'Central Europe Standard Time'
6. 'Central European Standard Time'
7. 'W. Europe Standard Time'
8. 'E. Europe Standard Time' 

- If your database server time zone is different than your DNN portal time zone, your database server is in one of these time zones, and you want to take advantage of this conversion feature, temporarily set your DNN time zone to the server time zone prior to installing this update. 

- Once the module is installed, and the existing data is converted, you can then set your DNN time zone as desired.

## PR Template Checklist

- [X] Fixes Bug
- [X] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #86

### CODE REVIEW

**Comment by johnhenley** [comment]
database changes
image

**Comment by johnhenley** [comment]
@WillStrohl there is some overlap with #123 and #124 because of the sqlprovider file. I updated the sql provider file to include comments to delineate each update. Also the smtp update #124 updates the activeforums_queue table and then this PR also updates it. The "full" sql file for all PRs is in this pull request

**Comment by johnhenley** [comment]
### Impacted database objects 
**Table Defaults/Constraints** (updated from GETDATE() to GETUTCDATE)
 
 DF_activeforums_AuditLog 
image

DF_activeforums_Content  
image
 
DF_activeforums_Forums   
image
 
DF_activeforums_Forums_Tracking  
image

DF_activeforums_Poll_Results
image
 
activeforums_SearchCache  
image

DF_activeforums_Templates 
image

DF_activeforums_Topics_Ratings   
image

**Comment by johnhenley** [comment]
### Impacted database objects 
**Views** (updated from GETDATE() to GETUTCDATE() )
  
[vw_activeforums_ForumTopics] 
image

[vw_activeforums_Security] 
image

**Comment by johnhenley** [comment]
### Impacted database objects 
**Functions** (updated from GETDATE() to GETUTCDATE() )
  
**Functions** |  
[activeforums_GetForumSecurity]
image

**Comment by johnhenley** [comment]
### Impacted database objects 

**Stored procedures**   
[activeforums_Attachments_Save] 
image
 
[activeforums_Forum_Save] 
image
 
[activeforums_Forums_Maintenance]
image

[activeforums_Forums_Tracking_UpdateUser] 
image
 
[activeforums_ForumsList]
image
 
[activeforums_Poll_Save] 
image

[activeforums_Queue_Add] 
**(Note also includes PortalId associated with #124)**
image
 
[activeforums_Search] image

[activeforums_Search_FullText] 
image
 
[activeforums_Search_Standard] 
image

[activeforums_Templates_Save] 
image

[activeforums_Topics_Tracking_UpdateUser]
image
 
[activeforums_UI_ActiveView]  
image
 
[activeforums_UI_TopicsView] 
image

[activeforums_UI_TopicView] 
image

[activeforums_UI_TopMembers] 
image

[activeforums_UserProfiles_Create] 
image

[activeforums_UserProfiles_Get] 
image

[activeforums_UserProfiles_GetUsersOnline]
image

[activeforums_UserProfiles_List] 
image

[activeforums_UserProfiles_Save] 
image

[activeforums_UserProfiles_Stats] 
image

[activeforums_UserProfiles_UpdateActivity] 
image

[activeforums_Util_MarkAsRead] 
image

**Comment by johnhenley** [comment]
:) let me know if you have any questions etc.

**Comment by johnhenley** [comment]
Not sure there's an easier way to handle the sql changes across pull requests. I've been stacking them in the same file in order by pr# so hopefully you get them in the correct order. For instance there is a change in this pull request that supersedes one in #124. Only other option might be to put them in separate files but that might get them out of order. Any suggestions?

**Comment by WillStrohl** [comment]
Hey @johnhenley , quick question since you've done all of this awesome work...  Once we merge this and put out a public beta release, what would you say are the best 3 (or so) tests we can ask people to perform to test their own environments for any bugs resulting from this update?  

It's pretty substantial, so I think that we should give people something to go off of.  What do you think?

**Comment by johnhenley** [comment]
> Hey @johnhenley , quick question since you've done all of this awesome work... Once we merge this and put out a public beta release, what would you say are the best 3 (or so) tests we can ask people to perform to test their own environments for any bugs resulting from this update?
> 
> It's pretty substantial, so I think that we should give people something to go off of. What do you think?

Hi @WillStrohl. 
1.  Conversion of existing dates/times. Pay attention to server time zone vs. DNN portal time zone setting. If server is already set as UTC, no conversion is done. Otherwise, make sure Portal time zone matches server time zone. Conversion is a one-time process, so it's either going to go well, or not. :) We may find that this is too much of a risk / burden, and just allow historical data to remain as is, and only have this functionality affect new posts going forward. As for my site, it's been in different data centers and was never (re-)set correctly, neither on the server nor in the portal settings. It was set on the server as EST and in the portal as CST because it was previously in a data center in CST. I left the server as EST, changed the portal to EST, ran the update scripts, and then changed everything to UTC. 
2. View topics lists and "what's new" module as different (authenticated users with different time zone preference as well as unauthenticated). Ideally, admins should do this before and after installing the updated module in their test environment to see effects of the data conversion. The what's new module actually used to work almost correctly.
3. Test email notifications (I use a utility called papercut, but I know there are some folder-based approaches that others use where the emails go to disk rather than to an SMTP server.) When testing, I made sure that rendered emails had correct topic times based on recipients' offset preference. This will be the biggest change since all emails used to have the same time based on portal settings.

**Comment by johnhenley** [comment]
@WillStrohl @Timo-Breumelhof 
Hopefully I didn't scare you guys off? Any updates on a new release?

**Comment by WillStrohl** [comment]
Not scared off... Just busy keeping up with the ebb and flow of client work and trying to balance that with open-source work.  (Just like most of us.)  

I'm hoping to get back to these PRs in the next week.  :)

**Comment by Timo-Breumelhof** [comment]
Hi @johnhenley, same here, your contributions are very much appreciated :-)
Just too much work ATM..

**Comment by WillStrohl** [comment]
Agreed and I echo the accolade and appreciation from Timo!  :) 

This is going to be so awesome for the entire community...  Thank you!

**Comment by WillStrohl** [comment]
Nice catch on the typo.  :)

**Comment by johnhenley** [comment]
> Nice catch on the typo.  :) 

I had deployed an internal build to my lawsonguru.com site to dogfood these changes. I did the sql manually and just copied the DLL rather than create the full install, but so far no issues and I've actually had a user who noticed that the paging issues were fixed :)

**Pull request merged**
