### PR TITLE
Changes for #503 generate Source package with Gulp

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**
### Description of PR...
I added Theme source packaging to gulp.

* We also need to exclude the gulp and less files from the install package IMO  *

## Changes made
- Added "gulp source" command support

## How did you test these updates?  

Local install

## PR Template Checklist

- [ ] Fixes Bug
- [x] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #

### CODE REVIEW

**Comment by Timo-Breumelhof** [comment]
Hmm, did I make a mistake in my previous PR?
I now see that the templates are commited as "new" while I already committed them IMO..
@WillStrohl @johnhenley ?

**Comment by WillStrohl** [comment]
I don't know.  This is why John and I had to find a cadence to review and approve the PRs together in a specific order.  It's difficult to say without beginning to approve the PRs and/or starting them over.  :(

**Comment by johnhenley** [comment]
> Hmm, did I make a mistake in my previous PR?
> 
> I now see that the templates are commited as "new" while I already committed them IMO..
> 
> @WillStrohl @johnhenley ?

@Timo-Breumelhof I think you removed them in PR 579, so I asked in this comment:

https://github.com/DNNCommunity/Dnn.CommunityForums/pull/579#issuecomment-1789634358

BTW sorry I've been silent for a while working on a project and haven't had any time for forums:(

**Comment by Timo-Breumelhof** [comment]
@johnhenley @WillStrohl Hmm, I see now. I have no idea why the templates are missing from #501 but I'll cancel this PR and first commit the templates correctly..

**Pull request closed without merging**
