### PR TITLE
Remove outdated AF 4.3 template files

### LINKED ISSUE #175: Remove outdated AF 4.3 template files
## Please summarize your question in one sentence
Remove outdated AF 4.3 template files

### PR DESCRIPTION
**Pull request by johnhenley**
Remove outdated AF 4.3 template files
Close #175

### CODE REVIEW

**Comment by WillStrohl** [comment]
Do you think we should do a diff at the next release to create a `cleanup` file+component, or start that in this PR? I'll defer to your preference.

**Comment by johnhenley** [comment]
> Do you think we should do a diff at the next release to create a `cleanup` file+component, or start that in this PR? I'll defer to your preference.  

I will create one and amend to this

**Comment by valadas** [comment]
Not sure if it helps this situation but I added globbing patterns support for cleanup in DNN 9.5.0 https://docs.dnncommunity.org/content/tutorials/extensions/dnn-manifest-schema/index.html#components

**Comment by johnhenley** [comment]
> Not sure if it helps this situation but I added globbing patterns support for cleanup in DNN 9.5.0 https://docs.dnncommunity.org/content/tutorials/extensions/dnn-manifest-schema/index.html#components

Currently the Forums module uses DNN 9.4 so that won't work unless we change that baseline requirement. And probably should:)

**Pull request merged**
