### PR TITLE
ENH: Show login link on TopicView page if unauthenticated rather than "you are not authorized"

### LINKED ISSUE #781: ENH: Link to Login when not logged in and viewing a topic
## Is your feature request related to a problem?
This one is just annoying. If I haven't logged in, and I'm viewing a topic, I see a message "you are not authorized to post a reply". Just rude, IMHO :)

image

## Describe the solution you'd like
Put in a link to the login page with a friendlier message.

## Describe alternatives you've considered
I've "solved" this previously by patching in a URL via the resources, but we should just support a standard DNN token for the URL that inserts the URL, and add that to the TopicView template.

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Show login link on TopicView page if unauthenticated rather than "you are not authorized"

## Changes made
- If unauthenticated, show link with message to login
- Add string resource to SharedResources: [RESX:NotAuthorizedReplyPleaseLogin]: 
`Please <a href="{0}">login</a> to post a reply.` where {0} is replaced with Portal's login URL.

## How did you test these updates?  

Local install 
image

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #781

### CODE REVIEW

**Review by Timo-Breumelhof — COMMENTED** [review]
Looks good, but IMO we should not render one inside a span and another without.
Also, when we add a span I would render a class with the status so  you can address them accordingly.

Example: 
`<span class="dcf-auth-false-login">`
vs
`<span class="dcf-auth-false">`
Now I could use:
.dcf-auth-false-logi{
color: red;
}

IMO the "afnormal" class is useless and can be removed?

@johnhenley what do you think?

**Comment by johnhenley** [comment]
> Looks good, but IMO we should not render one inside a span and another without. Also, when we add a span I would render a class with the status so you can address them accordingly.
> 
> Example: `<span class="dcf-auth-false-login">` vs `<span class="dcf-auth-false">` Now I could use: .dcf-auth-false-logi{ color: red; }
> 
> IMO the "afnormal" class is useless and can be removed?
> 
> @johnhenley what do you think?

updated to wrap both in span tags
image

**Comment by WillStrohl** [comment]
@Timo-Breumelhof @johnhenley  I'm okay with it either way, by the way.  I just wanted to pose the question.  Since we're touching it, do we want to update how it looks, or no?

**Comment by johnhenley** [comment]
> @Timo-Breumelhof @johnhenley Looking at the discussion above, should I assume that we're going to have a PR later to make the login prompt more obvious, or are we okay with it blending into the rest of the controls on the page?

@WillStrohl I would just merge it as it is right now so that it's in the release. If @Timo-Breumelhof has time and wants to re-style, he can do it.

**Pull request merged**
