### PR TITLE
DOC: Project readme and code of conduct 

### LINKED ISSUE #372: Add a useful README to the project
## Description of task
As of right now, there isn't a `README` associated to this project.  This task is for us to consider whether or not to add one, and what it should contain.  This is a great opportunity for us to get it as close to being "correct" on the first push.  :)  

What I'm thinking it should include might be:  

- What is the community forums module?  
- Who is currently maintaining the module?  
- How do you find help for the module?  
-- Persona-Based: developers, end-users, administrators, moderators, etc.  
- How do you help contribute code to this module?  

## What general area(s)/component(s) are affected?  

[] User interface  
[] Database schema  
[] Business Logic  
[] Dependencies  
[] Installation/manifest  
[x] None of the above  

## Additional context
Add any other context or screenshots about the task here.

### PR DESCRIPTION
**Pull request by WillStrohl**
### Description of PR...

Adding a `readme` to help new visitors know where they are and why.  It helps to point people to places for help, what they need to know about DNN compatibility, and how they can help us.  

I also updated some other markdown files related to GitHub.  

## Changes made
- Added our first `README`  
- Added a GitHub code of conduct template, sourced from another DNN core extension  
- Updated the PR template to include more information  

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #372

### CODE REVIEW

**Review by johnhenley — APPROVED** [review]
I did fix a couple of words, but overall these look fine to me, and I appreciate you working on them! 

Two comments/questions:
1. this module sorely needs a 'getting started' document to be referenced from the 'how to install' section :)
2. in the readme, shouldn't we direct them to the github discussion first, since that is specific to this module? The other two forums on dnncommunity.org are generic to all extensions/modules, correct? The text you put in for the link implies that they are specific for this module.

**Comment by WillStrohl** [comment]
The first point is a great one...  I'll work on that now.  

The second point is good too.  The intent isn't to say that those are official places for this module.  It really is to encourage use of the module, but that makes sense.  I'd be pointing other people to the respective issues/discussions at some point for another module.  :)

**Comment by johnhenley** [comment]
> The first point is a great one...  I'll work on that now.  
> 
> 
> 
> The second point is good too.  The intent isn't to say that those are official places for this module.  It really is to encourage use of the module, but that makes sense.  I'd be pointing other people to the respective issues/discussions at some point for another module.  :) 

How about if I put a lot of stuff from the original documentation into the wiki?

**Comment by WillStrohl** [comment]
> How about if I put a lot of stuff from the original documentation into the wiki?

That is definitely something we should do at some point.  :) 

I've added a getting stated section in my most recent commit.

**Pull request merged**
