### PR TITLE
ENH: Store and retrieve templates to/from file system

### LINKED ISSUE #93: Change Templates to Cached File based
## Is your feature request related to a problem?
**Please describe.**
Editing and testing Forum Templates is cumbersome because the templates are in the database.
File based templates would make creating templates much easier.

The reason I think templates should be file based are the following:

- Portability
- Simplicity
- Editability
- Versioning

Creating a template for the module is a real pain ATM.
The module gets the default templates from file (“ActiveForums\config\templates”)
When you create a custom template these are stored mainly partly in the database and partly in “ActiveForums\themes”.
(where there's also a Module.css which we should get rid of IMO as it has way too specific CSS)
For editing you need to go into the edit screen in the module and edit your ascx there, and many time you need to restart DNN for your change to be picked up.

I started creating a Bootstrap 4 template for dnncommunity.org a long time ago and it took me at least 3 to 4 times as long due to constantly having to restart the DNN and the cumbersome edit interface for templates.
And then when I wanted to move them from my local machine to the live site, I had to copy them one by one into the edit screen and also save some separate txt file to be able to put them in versioning somehow.
Not very good for my motivation ATT if I'm honest, way too many hoops to jump through...

File based templates from a single folder (so there's not some random CSS you need to overwrite) would make the creation of Templates way more efficient and also fun TBH. :-)

Also, some people asked for these templates and they are currently much more difficult to share compared to a simple file based approach. See: https://github.com/DNNCommunity/Dnn.CommunityForums/issues/92

I think we could offer 3 possible locations:

For the default templates that come with the module:

- /Desktopmodules/AciveForums/Tempaltes

We should however add a note to these templates that they should not be edited.?
(overwrite on upgrade)

- Portals/_Default/ActiveForums/Templates > For all all portals
- Portals/PortalFolder/ActiveForums/Templates > a specific folder

## Describe the solution you'd like
Load the templates (*.ascx)  form a "templatename" folder.

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Editing and testing Forum Templates is cumbersome because the templates are in the database. File-based templates makes creating and maintaining templates much easier.

### Changes made 

- Templates are now retrieved from .txt files rather than database

- During upgrade, templates existing in the database table `activeforums_templates` are extracted to `~/DesktopModules/ActiveForums/{theme}/templates/` based on the theme associated with the template's module instance. Templates not associated to a module instance are written to `~/DesktopModules/ActiveForums/{theme}/templates/`

- Template files are named using the template's "title", e.g., ForumView.txt. If multiple templates with the same name exist within the same instance of the Forums module installed on the DNN host, the template file names are made unique by appending the ModuleId and TemplateId from `activeforums_Templates` to the filename, e.g., TopicView-43-18.txt.

- When loading templates at runtime, they are loaded from (in high-to-low priority order): 
- `~/DesktopModules/ActiveForums/{theme}/templates/`
- `~/DesktopModules/ActiveForums/templates/`
- `~/DesktopModules/ActiveForums/config/templates/` (delivered templates)

- Templates can either be edited directly on the server or can still be edited using the template editor in the Forums module. The template file name is displayed in the template editor:

image

### PR Template Checklist

- [ ]  Fixes Bug
- [X]  Feature solution
- [ ]  Other

### Please mark which issue is solved
Closes #93

### CODE REVIEW

**Comment by johnhenley** [comment]
@WillStrohl @Timo-Breumelhof Since previous PR #194 was just too big for good testing, I canceled it and I'm moving some of those changes into earlier PRs (like #226 for removing hardcoded paths). I will also be creating additional future PRs for moving templates to host folder rather than desktopmodules, moving themes to host folder rather than desktopmodules, and packaging up the themes from dnncommunity.org.

**Comment by Timo-Breumelhof** [comment]
Ok seem logical, thank you:-)

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Comment by WillStrohl** [comment]
@johnhenley These should be easy to remedy.  :)

**Comment by johnhenley** [comment]
> @johnhenley These should be easy to remedy. :)

done i hope :)

**Comment by WillStrohl** [comment]
Yep, we're good this time!  :)

**Pull request merged**
