### PR TITLE
ENH: Improvements and fixes to topic splitting

### LINKED ISSUE #780: BUG: Fix multiple issues with "split" feature
## Describe the bug
There is a great feature in the Forums module, but it needs some love.
If you add some tokens to the TopicView.ascx template, and you're a moderator, you can split selected replies from a thread into a different thread, in a different or same forum. 

## Software Versions
- DNN: 09.13.03
- Module: 08.00.01

What needs to be addressed:
1. The [SPLITBUTTONS], [SPLITBUTTONS2], and [SPLITCHECKBOX] need to be in the TopicView template, so they need to be added to the TopicView template shipped with the community-default and community-bootstrap themes.
2. There are some styling issues with how the buttons appear that should be cleaned up (i.e. the 'Save' and 'Cancel' buttons are initially visible but should only show up if you actually click 'Split' :) )
3. An error is displayed when the split is performed, which needs to be diagnosed and fixed.
4. The new (friendly) URL is not created when the new topic thread is created (you have to edit then save the topic, which creates the URL.

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Fixes several issues and improvements for topic splitter.

## Changes made
- Load split buttons panel HTML from template rather than hard-coded
- Add new dcf- prefixed CSS classes; added placeholders to module.css
- Add [SPLITBUTTONS] and [SPLITCHECKBOX] tokens to Community-default and Community-bootstrap TopicView templates
- Move splitter javascript from afcommon.js to afmod.js (only moderators can split topic)
- Resolved 'error splitting' after Web API call
- Friendly URL was not being created for split topic
- Fixed issues with Replies_Split stored procedure
- Minor tweaks to javascript/CSS

## How did you test these updates?  

Local install.

1. A topic with replies, view by a moderator with "split" security will now show a 'Split' button:
image

2. When you click the 'Split' button, you are then put into 'Split Mode'; 1) select the desired replies to be split to a different topic, and 2) click 'Save':
image

3. You can split the selected posts to go to a new or existing topic, in same or different forum:
image

image

## PR Template Checklist

- [X] Fixes Bug
- [X] Feature solution
- [ ] Other
- [x] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark#780 ch issue is solved

Close #780

### CODE REVIEW

**Review by Timo-Breumelhof — COMMENTED** [review]
@johnhenley I love the fact that you improved this.
From a UX poijt of view, I so wonder if we should make the split checkbox a bit clearer?
Also I think it would be better if they would be on the right side next to "move" with a label "split"? (If that is at all possible).
(maybe in v9?).

**Comment by johnhenley** [comment]
> @johnhenley I love the fact that you improved this.
> 
> From a UX poijt of view, I so wonder if we should make the split checkbox a bit clearer?
> 
> Also I think it would be better if they would be on the right side next to "move" with a label "split"? (If that is at all possible).
> 
> (maybe in v9?).

It's a token [SPLITCHECKBOX] so it can go anywhere. I thought about putting a label next to it but that got more involved and I had spent enough time on it already with my limited skillset :)

**Comment by Timo-Breumelhof** [comment]
> > @johnhenley ...I had spent enough time on it already with my limited skillset :)

hahaha :-)

**Comment by Timo-Breumelhof** [comment]
@johnhenley There seem to be an lot of changed file after your last commit...?

**Comment by johnhenley** [comment]
> @johnhenley There seem to be an lot of changed file after your last commit...?

Yes, I made the mistake of changing something unrelated that was annoying me. When you're in the browser tools, it became apparent that some of the files are loaded from "activeforums" and some from "ActiveForums", so I changed them to be consistent...

image

**Comment by johnhenley** [comment]
> @johnhenley I love the fact that you improved this. From a UX poijt of view, I so wonder if we should make the split checkbox a bit clearer? Also I think it would be better if they would be on the right side next to "move" with a label "split"? (If that is at all possible). (maybe in v9?).

@Timo-Breumelhof in your honor:
image

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Pull request merged**
