### PR TITLE
ENH: Add 'ban user' options to forum moderation

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Adds 'ban user' functionality when reviewing posts for moderation

## Changes made
- Add 'Ban' moderation action to Notifications activity feed
- Add 'Ban' moderation action to Forums Moderate 

## How did you test these updates?  
local install

image
image

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already

### CODE REVIEW

**Comment by johnhenley** [comment]
@WillStrohl one more for you

**Review by Timo-Breumelhof — COMMENTED** [review]
Great improvement :-)

**Comment by johnhenley** [comment]
@WillStrohl this is ready for you to review

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Pull request merged**
