### PR TITLE
change email API usage to pass smtp information

### LINKED ISSUE #96: Email Sending Error: Portal Specific SMTP setting ignored
## Please summarize your question in one sentence

Emails from Active Forum are not sending using the portal specific SMTP configurations

## Give a more extended description
I discovered that emails sent via Active Forum are not using the portal specific SMTP configuration. 

The emails were working fine in the past, but stopped recently. After investigation I found that the reason they stopped working is the host SMTP server configuration was not longer configured correctly to send out emails. This issue is not related to a recent upgrade to DNN 9.9.1.

DNN 9.9.1 install with version 6.6.0 of Active Forums installed.

## Steps to reproduce (if needed)

Using the tip from Timo-Breumelhof I setup the installation to store eml files in a local server pickup folder. I configured the portal SMTP to use the localhost configuration. Emails were not sent to the pickup folder. When I configured the host SMTP server with the same configuration, the emails were saved into the pickup folder. 

This is an indication that active forum is not looking at the portal SMTP server settings if they are configured.

### PR DESCRIPTION
**Pull request by johnhenley**
## Changes made
-  Use more elaborate DNN API that allows passing of the SMTP information; behind the scenes, the DNN API DotNetNuke.Host.SMTP property accessors determine portal vs. host SMTP values 

## PR Template Checklist

- [X] Fixes Bug
- [ ] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #96

### CODE REVIEW

**Comment by johnhenley** [comment]
Digging into the platform code, it looks like it does this already if you can the simpler SendEmail api. So you may want to reject this and/or have person who created the issue do more triage?

**Comment by johnhenley** [comment]
@Timo-Breumelhof: Indeed that does appear to be the case... for now I am closing this and will go back to the drawing board...

**Comment by johnhenley** [comment]
> @Timo-Breumelhof: I re-opened this pull request but reverted my code update in order to continue the discussion. Should that discussion happen here, or on the issue itself?

**Comment by Timo-Breumelhof** [comment]
@johnhenley Discussion @ the Issue IMO. :-)

**Comment by Timo-Breumelhof** [comment]
@johnhenley For clarity, I would not re-open a PR though if you decide to solve the issue in a different way, but create a new one..

**Comment by johnhenley** [comment]
ok. closing.

**Pull request closed without merging**
