### PR TITLE
ENH: Enable template-based UI for Quick Reply

### LINKED ISSUE #348: ENH: Add template support for Quick Reply
## Is your feature request related to a problem?

In order to properly implement a better layout for quick reply, replace current hard-coded control with templated control. Move current hard-coded HTML to default template, and template editor. That will support implementing pull requests for this issue:
Currently the Quick reply box does not work very well on mobile..

image

## Describe the solution you'd like
Make sure it's as easy to use as possible on Mobile. :-)

## Additional context
The quick reply editor is wrapped in a table, we should really use div and flexbox here so we can make sure the title is above the text box and the text box is full width..

_Originally posted by @Timo-Breumelhof in https://github.com/DNNCommunity/Dnn.CommunityForums/issues/305_

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Quick Reply has previously been hard-coded and used a table structure for UI.
Providing the ability to edit/layout the Quick Reply UI via a template.
This allows designers to layout/style the UI however they want.

## Changes made
- restructured quick reply code to load from a template
- converted current default (table-based) quick reply to be a template
- added some simple tokens/replacements for the template based on current template
- updated wiki / documentation for tokens / Quick Reply template (https://github.com/DNNCommunity/Dnn.CommunityForums/wiki/Quick-Reply-Template)
- added quick reply as a template type 
- updated control panel to allow selection of Quick Reply template for forum groups/forums
- created a new div-based Quick Reply template as part of the "community" theme (@Timo-Breumelhof: please style :))
- change default for new install to use the delivered "community" theme's Quick Reply template

## How did you test these updates?  
- Build against 08.00.00 dev branch.
- Test using default (table-based) 
image

- Test against community (div-based) quick reply (needs styling)
image

Tested forums control panel.
image

image

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [X] I've updated the documentation already  

## Please mark which issue is solved

Close #348 
Enables #305

### CODE REVIEW

**Comment by johnhenley** [comment]
@Timo-Breumelhof This is ready for you to do some styling on the div-based template in the community theme. \DesktopModules\ActiveForums\themes\community\templates\QuickReply.txt

**Comment by johnhenley** [comment]
@WillStrohl Do you want to try and get this into 08.00.00? I think this (#305) was one of the main design goals we had originally hoped to achieve :) ?

**Review by Timo-Breumelhof — COMMENTED** [review]
Looks good to me.

**Comment by Timo-Breumelhof** [comment]
@johnhenley @WillStrohl I think we should add this to 08.00.00? 
Can I merge this one or does it depends on other commits /  a certain order?
I want to spend time on this next week..

**Comment by johnhenley** [comment]
@Timo-Breumelhof @WillStrohl this PR can stand alone. So it can either go into 08.00.00 or be held out for later.

**Comment by Timo-Breumelhof** [comment]
@johnhenley I think this is a great improvement so I'll make time for it :-)

**Pull request merged**
