### PR TITLE
BUG: Make sure Filter dropdown texts are visible on Mobile

### LINKED ISSUE #959: ENH: Excess whitespace on mobile devices for Filtered topics drop-down
On mobile devices, text is not shown. Remove extra whitespace or show text. 
image

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**
### Description of PR...
Icon texts are hidden on Mobile and this influenced the filter dropdown texts too.
This PR excludes these texts from being hidden

## Changes made
- community-default Theme
- community-bootstrap Theme

## How did you test these updates?  

Local install

## PR Template Checklist

- [ ] Fixes Bug
- [x] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #959

### CODE REVIEW

**Comment by Timo-Breumelhof** [comment]
@johnhenley 08.01.02? or 08.02.00 ?

**Review by johnhenley — CHANGES_REQUESTED** [review]
@Timo-Breumelhof I think I posted the issue too quickly and not clearly. What should happen on mobile is just show the icon without the text. The screenshot I included was to show that there is extra whitespace where the text would be. I think for mobile we should just show the icon/get rid of the whitespace and not show any text. That is consistent with the way the toolbars behave on mobile. Which is great BTW.

**Comment by Timo-Breumelhof** [comment]
@johnhenley I think we are removing icon texts for mobile because of lack of space. But in this case there's not space issue and I don't think I would understand the content of the dropdown without those texts TBH.

**Comment by johnhenley** [comment]
Ok. Then just put it in :)

**Comment by Timo-Breumelhof** [comment]
I did ;-)

**Comment by johnhenley** [comment]
> @johnhenley 08.01.02? or 08.02.00 ?

Whatever is next release. I'm hoping we don't need 08.01.02

**Pull request merged**
