### PR TITLE
ENH: Improved Caching

### LINKED ISSUE #258: Improved Caching
## Implement Caching improvements:
- repeated file reads for config/tokens.config (every topic page view)
- module settings are not properly cached resulting in multiple calls to DNN platform API (this is improved in issue #252 by changing API, but this can be further improved by caching settings and not needing to call the API repetitively
- cache keys are not centrally-located

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Updates caching throughout the Forums module

## Changes made
- Topics View and Topic view are now cached
- Caching keys are now centrally located in one location in the codebase
- Refactor/correct logic where items were cached and not retrieved, cleared when not cached, etc. 
- Caches are now module-specific, so if multiple forums instances are used, they are now isolated
- Code referencing SiteId has been updated to PortalId
- Code referencing InstanceId has been updated to ModuleId
- Simplify cache clearing; if you use the control panel, cache is entirely cleared
- Settings are now cached for 10 minutes regardless of module cache setting
- Content (posts) are cached for 2 minutes regardless of module cache setting
- New module setting added to enable/disable template caching (enabled by default; disable if testing templates)

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #258

### CODE REVIEW

**Comment by WillStrohl** [comment]
When we get closer to being able to merge this PR, we'll probably need you to do a quick merge and conflict resolution on this PR first.  :)

**Comment by johnhenley** [comment]
> When we get closer to being able to merge this PR, we'll probably need you to do a quick merge and conflict resolution on this PR first.  :) 

Definitely. I'm just trying to work on merge conflicts one release at a time.

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Comment by WillStrohl** [comment]
@johnhenley  I spoke too soon, in email.  There are many conflicts.  :(

**Comment by johnhenley** [comment]
And don’t bother trying to build because the merge clobbered a few files:(. I will have to look into it and don’t want to rush it.

John
________________________________

**Comment by WillStrohl** [comment]
Sounds good.

**Comment by johnhenley** [comment]
> Sounds good.

Did you clean it up for me?

**Comment by WillStrohl** [comment]
No. I thought you did.  🤷🏽‍♂️

**Pull request merged**
