### PR TITLE
ENH: Show theme and template folder in Control Panel templates list

### LINKED ISSUE #569: ENH: Show current Theme when editing Templates
## Is your feature request related to a problem?
**Please describe.**
When you edit Templates, it would be nice if you could see what Theme you are currently in.
I mean in this screen:

image

## Describe the solution you'd like
Show the currently selected Theme 

Something like this:

image

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Add theme name and template folder to Control Panel templates list

## Changes made

- UI updates
- Added resource strings to ControlPanel.resx:
  - [RESX:Template] 
  - [RESX:Theme] 
- Added resource strings to SharedResources.resx:
  - [RESX:Folder] 

## How did you test these updates?  
Local install
image

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #569

### CODE REVIEW

**Review by Timo-Breumelhof — COMMENTED** [review]
Nice addition :-)

**Comment by Timo-Breumelhof** [comment]
@johnhenley Hmm, I guess I should have merged them in another order :-(

**Comment by johnhenley** [comment]
> @johnhenley Hmm, I guess I should have merged them in another order :-(
Merge conflicts seem to be my specialty :)
That's why I usually only do one PR at a time.
Try this one again. Then do PR #664, #665, and #666. Then I will resync again and push another one.

**Comment by Timo-Breumelhof** [comment]
@johnhenley done

**Pull request merged**
