### PR TITLE
Call correct cache clearing API when moving topic

### LINKED ISSUE #65: Forum overview Thread count not updating after moving Thread to other forum
## Describe the bug
When you move a thread to another forum, the number of posts in the overview is not updated until you clear the cache.

## Software Versions
- DNN: 09.08.00
- Module: 06.05.00

## To Reproduce
1. Create 2 forums, 1 & 2
2. Create a Thread in Forum 1
3. Check the number of posts in forum 1 on the Forum overview page
4. Move the Thread to Forum 2
5. You will see in the overview that the thread count is still 1 in forum 1 until you clear the DNN Cache

## Expected behavior
Correct Post Count

### PR DESCRIPTION
**Pull request by johnhenley**
## Changes made
- Call correct cache clearing API when moving topic (previous call was to clear cache for forum settings/templates not content)

## PR Template Checklist

- [X] Fixes Bug
- [ ] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #65

### CODE REVIEW

**Comment by Timo-Breumelhof** [comment]
Great, thanks again for spending time on this :-)

**Comment by WillStrohl** [comment]
I agree with the advice given by @Timo-Breumelhof.  In general, refactoring is good, but we should do it carefully and in planned phases.  We shouldn't do it as part of a different update, in my opinion.  

For example, an issue and then PR that simply updates interpolation strings would be great.  Then, a separate issue and PR can be used for the next optimization.  

If something minor is found within a specific update that's related, that would be different and fine when included.  For example, creating an optimization within the current class file that has other updates can be fine - but it depends on the risk of the specific update in general.  This would be determined on a case-by-case basis.  It's not always clear where the line is.  We just need to continue to chat about it like we are now, whenever we all want to figure something like this out.

**Comment by johnhenley** [comment]
A lot of debugging and working thru the code :)
image
this is the code in ForumController.cs that sets the cache for the "forum view" 
when clearing the caches, you can specify just the prefix, e.g. AF-FV-{portalId}-{moduleId} to clear the forum view cache for all users for the instance of AF on portalId/moduleId.

Does that answer your question?

**Comment by WillStrohl** [comment]
Did you intend to close and delete this PR?

**Comment by johnhenley** [comment]
@WillStrohl Oops. Another GitHub rookie mistake I guess. I renamed my local branches (I changed from bug/# and task/# to issue/# so they line up better in visual studio ...) and I guess that screwed up the linkage to remote. 
Let me see if I can unscramble this and the other ones

**Comment by WillStrohl** [comment]
We'll eventually want to turn a format value like that into a constant, but this is fine for now.  Thanks for your contribution!

**Comment by johnhenley** [comment]
> We'll eventually want to turn a format value like that into a constant 
@WillStrohl yeah. there seem to be a lot of those...

**Comment by WillStrohl** [comment]
Indeed.  Too many.  😁

**Pull request merged**
