### PR TITLE
ENH: Implement Process Queue

### LINKED ISSUE #376: ENH: Implement Process Queue
## Offload work from UI

This is related to epic issue #164. 
Please refer to that issue for broader overview/context. 

Specifically this task:

- Implements a more generic queuing controller which will become the base for any type of queued work 
- implements a "new post" queue which handles any workflow actions  currently handled in the UI and forces the user to wait. Examples are the reordering of previous/next pointers between topics, and updating last update timestamps, etc. Adding an single entry to "new post" queue should be all that is done vs current logic which looks up subscribers and queues each individually. 🙃 
- Moves notification code out of the UI and into the "new post" queue. This includes handling moderation notifications as well as regular notifications. 
- Moves processing tasks (updating last post/reply dates and forum topic previous/next pointers) out of UI

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
- Implements a more generic queuing controller which becomes the base for any type of queued work, with the goal being to move as much of database updates, workflow actions, etc. out of the UI thread, and not forcing the user to wait. Examples are the reordering of previous/next pointers between topics, and updating last update timestamps, etc. Adding a single entry to the process queue should be all that is done from the UI thread vs current logic which looks up subscribers and queues each notification individually. 🙃
- Moves email notification code out of the UI and into the process queue. 
- Moves processing tasks (updating last post/reply dates and forum topic previous/next pointers) out of UI

## How did you test these updates?  

Local install
image

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #376

### CODE REVIEW

**Comment by johnhenley** [comment]
@WillStrohl another "year in the making" update (this dates back to last May!), this is last major PR for 8.1....after this is merged, I will do some additional testing / stabilization but no new features.

**Comment by johnhenley** [comment]
> @WillStrohl another "year in the making" update (this dates back to last May!), this is last major PR for 8.1....after this is merged, I will do some additional testing / stabilization but no new features.

P.S. "Never again" will I work this far ahead of a release....nearly killed me with stale branches and merge conflicts :)

**Comment by Timo-Breumelhof** [comment]
> > @WillStrohl another "year in the making" update (this dates back to last May!), this is last major PR for 8.1....after this is merged, I will do some additional testing / stabilization but no new features.
> 
> P.S. "Never again" will I work this far ahead of a release....nearly killed me with stale branches and merge conflicts :)

haha I can imagine.. :-)

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Pull request merged**
