### PR TITLE
ENH: Relocate/remove upgrade code associated with very old versions

### LINKED ISSUE #298: Refactor old upgrade code
## Description of task
There are a few blocks of code that upgrade settings and that run EVERY time the forums module is accessed. These were associated with v4->5 and v5->6. They have been retained to maintain compatibility when installing newer versions. But with having IUpgradeable support added in #188, they can be moved to the upgrade code, and run once and never again. 

## What general area(s)/component(s) are affected?
** check any / all **
[] User interface
[] Database schema
[X] Business Logic
[] Dependencies
[X] Installation/Upgrade

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Refactor/remove upgrade code from very old versions

## Changes made
- Removed code that migrated forum permissions from v3 to v4 
- Probably no longer needed., but relocated code that upgraded module settings (circa v5 or v6) from activeforums_settings (key:GEN) to DNN Platform ModuleSettings table; the check to execute this code was performed during every page load, and is now only checked during the module upgrade for 07.00.11. 

## PR Template Checklist

- [ ] Fixes Bug
- [ ] Feature solution
- [X] Other

## Please mark which issue is solved 

Close #298

### CODE REVIEW

**Comment by WillStrohl** [comment]
@johnhenley Since we're removing code in this update, I think it makes better sense to include this update in a minor release.  It poses a small, but real risk, I think.  What do you think?  Also, this may mean that we just wrap up everything remaining in the 7.00.11 and 7.00.12 milestones, and release it all in 7.1.  🤔

**Comment by johnhenley** [comment]
> @johnhenley Since we're removing code in this update, I think it makes better sense to include this update in a minor release. It poses a small, but real risk, I think. What do you think? Also, this may mean that we just wrap up everything remaining in the 7.00.11 and 7.00.12 milestones, and release it all in 7.1. 🤔

OK, that's fine with me. Just note that the IUpgradeable code in TopicsController, the cleanup file (07.00.11.txt) and associated manifest tag need to be updated. And there are SQL updates in 07.00.11 and 07.00.12 that need to be combined into 7.1.

**Comment by johnhenley** [comment]
> @johnhenley Since we're removing code in this update, I think it makes better sense to include this update in a minor release. It poses a small, but real risk, I think. What do you think? Also, this may mean that we just wrap up everything remaining in the 7.00.11 and 7.00.12 milestones, and release it all in 7.1. 🤔

Actually, I went back and looked, and I think it's worth the risk. The code that is being removed is associated with the _mechanics_ of upgrading from v3 to v4, but the _content/sql_ used to perform the upgrade has been long gone. And we are on v7. If someone is still on v3, they have a lot more to worry about, and can't expect us to maintain backward compatibility forever. The SQL installers for this module only date back to v4 anyway.

**Review by WillStrohl — APPROVED** [review]
Looks great!

**Pull request merged**
