### PR TITLE
Remove AddThis integration

### LINKED ISSUE #167: Remove AddThis
## Is your feature request related to a problem?
There is a feature that allows end-users to optionally choose to share the page using a third-party tool called [AddThis](https://www.addthis.com/).  The intent of such a feature is great, but this probably shouldn't have ever been added as a feature in this module.  

There are too many ways to implement the addition of a content-sharing feature like this.  Including what should be the correct (best practice) way in this case - adding it to the theme and/or creating a theme object that is added to the theme.  

Regardless, the module shouldn't be doing this and it usually should be done at the page-level.  

## Describe the solution you'd like  
Unless we can find a valid use case to do otherwise...  We should remove this feature entirely, including all API, UI, and schema that supports it.  

## Describe alternatives you've considered
None at this time.  

## Additional context
If implemented, this may be a breaking change for anyone that might be using this feature.  For example, many website owners operate on a "it works so don't touch it" kind of style.  So, they'll upgrade thinking the sharing feature is still there, only to find out it's not any longer.  Now, they'll have to scramble to figure out how to implement AddThis in another way.

### PR DESCRIPTION
**Pull request by johnhenley**
## Changes made
- Remove AddThis integration

## PR Template Checklist

- [ ] Fixes Bug
- [ ] Feature solution
- [X] Other

## Please mark which issue is solved

Close #167

### CODE REVIEW

**Comment by johnhenley** [comment]
> Awesome PR, @johnhenley !  (as always...)  
> 
> 
> 
> The only thing I see missing is the `cleanup` file and `component` update in the manifest file.  Do you want me to add that for you later?  

Hi @WillStrohl. Please add them. I didn't think a `cleanup` was needed since no files were removed?

Also this isn't meant to be a real release but I wanted to avoid the sqlprovider collisions that I created last time with multiple PRs using same version number. So I made this one 07.00.02. And I'm reserving 07.01.00 for the big kahuna PR that is coming for template changes #93. 
And any small intervening ones can be 07.0.xx.

**Comment by Timo-Breumelhof** [comment]
Sounds good :-) But Shouldn't we go to V8 for the template changes? 
As it's a breaking change?

**Comment by WillStrohl** [comment]
I agree with semantic versioning... I'm simply asking if we should target a major release for our next release.  😁

**Comment by johnhenley** [comment]
> When it contains the template change IMO it should be a major release.

Changing the storage location of templates might not be considered a breaking change. For new installations and upgrades, it's transparent but gives administrators option of editing templates by editing the files. Editing in the control panel still works. Same for moving themes out of desktopmodules. It's handled during installation and upgrades and doesn't require intervention. As long as it's well-tested and documented properly--that certain things have changed--like file names and locations. Just my two cents 😀

**Comment by johnhenley** [comment]
> I agree with semantic versioning... I'm simply asking if we should target a major release for our next release.  😁 

I'm undecided 😀.  On the one hand if we do, we're burning thru version numbers which is not good. But if we don't, we might be breaking something that people are using. Example is addthis. We've announced its removal and no feedback. I don't consider that a breaking change. If we release it as a minor release and document it, isn't that good enough?

**Comment by Timo-Breumelhof** [comment]
I agree it would be a bit fast on the other hand I so think it's a major change..

**Comment by WillStrohl** [comment]
I don't think it's possible for us to run out of version numbers.  :D  Let's keep the current version and adjust later based on the updates we see queued up, ready to be tested for release.  That should work for our process for now... Right?

**Comment by Timo-Breumelhof** [comment]
Agreed, let's decide later

**Comment by johnhenley** [comment]
@WillStrohl can you approve this?

**Pull request merged**
