### PR TITLE
FIX: Moderator action buttons not styled

### LINKED ISSUE #661: BUG: Moderate action buttons aren't styled (correctly)
## Describe the bug
Moderation buttons aren't styled (correctly).

## Software Versions
- DNN: 09.12.00
- Module: 08.00.01

## To Reproduce
1. Login as an administrator
2. Set a forum as moderated
3. Login as a regular user
4. Post to the moderated forum
5. Login as an administrator
6. Go to moderate page and see buttons shows as text (although they do perform the action).

## Expected behavior
Better looking buttons

## Screenshots
image

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Moderator action buttons (accept, reject, etc.) were not styled as buttons

## Changes made
- CSS styles for these items were inadvertently moved to "_Legacy" theme.css 
- Changed button styles to use standard DNN CSS classes

## How did you test these updates?  
Local install
image

## PR Template Checklist

- [X] Fixes Bug
- [ ] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #661

### CODE REVIEW

**Review by Timo-Breumelhof — COMMENTED** [review]
Hi John,

I would prefer not to set the font-family and font size this way.
Those are kind of things that are can look weird with custom DNN Themes.
When you want the text to be smaller I would use:

`font-size: 0.9em;`
So it scales according to the general Theme font size

And remove the 

`font-family: Tahoma;`

When this is exisitng CSS that's already in module.css, we can leave it this way and change in v9

**Comment by Timo-Breumelhof** [comment]
@johnhenley Ok I read your comment now.. I would say merge and I'll have a look at button styling for v9

**Comment by johnhenley** [comment]
> @johnhenley Ok I read your comment now.. I would say merge and I'll have a look at button styling for v9
> 
> 

Should they just use standard DNN button styles? I don't see a need to have a separate styling for this.

**Comment by Timo-Breumelhof** [comment]
> > @johnhenley Ok I read your comment now.. I would say merge and I'll have a look at button styling for v9
> 
> Should they just use standard DNN button styles? I don't see a need to have a separate styling for this.

Yes, IMO that would be better..

**Comment by johnhenley** [comment]
> > > @johnhenley Ok I read your comment now.. I would say merge and I'll have a look at button styling for v9
> > 
> > 
> > Should they just use standard DNN button styles? I don't see a need to have a separate styling for this.
> 
> Yes, IMO that would be better..

OK. I used my CSS skills : 
image

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Pull request merged**
