### PR TITLE
Made the Title and Summary input wider for both Themes #826

### LINKED ISSUE #826: Creating a new topic the subject is too small
When I go to create a new topic the subject input box is very small. It should take at least all available space:

image

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**
### Description of PR...

The Subject and Summary inputs are now wider, in both the community-default and the community-bootstrap theme

image

## Changes made
- Added a class to both element wrappers as I don't want to change the css class of the input in a minor version
- Added styling to make the inputs 95% wide

## How did you test these updates?  

Local install

## PR Template Checklist

- [ ] Fixes Bug
- [x] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #826

### CODE REVIEW

**Comment by johnhenley** [comment]
@Timo-Breumelhof 

I don't think this should be done per each theme but should be done at the module.

Can we just do this?

Change this:
image
to this:
image

change this:
image
to this:
image

add this to module.css:
image

**Comment by Timo-Breumelhof** [comment]
@johnhenley well we could, but I thought we will do this for a new big cleanup for v9?

**Comment by johnhenley** [comment]
> @johnhenley well we could, but I thought we will do that for a new big cleanup for v9?

I'd rather do it in the module for these two particular UI elements (subject and summary) than in the themes. Any (new or existing) theme should get this change.

**Comment by Timo-Breumelhof** [comment]
> > @johnhenley well we could, but I thought we will do that for a new big cleanup for v9?
> 
> I'd rather do it in the module for these two particular UI elements (subject and summary) than in the themes. Any (new or existing) theme should get this change.

Ok, I'll make the change

**Comment by johnhenley** [comment]
> > @johnhenley well we could, but I thought we will do that for a new big cleanup for v9?
> 
> I'd rather do it in the module for these two particular UI elements (subject and summary) than in the themes. Any (new or existing) theme should get this change.

(I'm also concerned that it takes so many file changes wi

> > > @johnhenley well we could, but I thought we will do that for a new big cleanup for v9?
> > 
> > 
> > I'd rather do it in the module for these two particular UI elements (subject and summary) than in the themes. Any (new or existing) theme should get this change.
> 
> Ok, I'll make the change

OK, let me know if you need anything.

**Comment by johnhenley** [comment]
> > > @johnhenley well we could, but I thought we will do that for a new big cleanup for v9?
> > 
> > 
> > I'd rather do it in the module for these two particular UI elements (subject and summary) than in the themes. Any (new or existing) theme should get this change.
> 
> Ok, I'll make the change

@Timo-Breumelhof I had a few spare minutes, so I did my version ( #851 )... you pick which one you want and cancel the other ...

**Review by WillStrohl — APPROVED** [review]
Looks good!

**Comment by WillStrohl** [comment]
@Timo-Breumelhof This PR has conflicts.  I think you're better suited to resolve them.  :)

**Pull request closed without merging**
