### PR TITLE
FIX: Incorrect links in pager when forum does not inherit group settings

### LINKED ISSUE #425: BUG: Paging not working
## Describe the bug
On the forum the paging is not working.  Clicking on page 2 will return you to the root forum.

https://dnncommunity.org/forums/aft/4714

## Software Versions
- DNN: 00.00.00
- Module: 00.00.00

## To Reproduce
1. goto forum
2. Click page 2

## Expected behavior
goto page 2

## Additional context

Other forums work, it's just the one listed above.

https://dnncommunity.org/forums/Getting-Started/new-to-dnn/application-error-in-dnn-site/2/

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Incorrect links in pager when forum overrides (does not inherit) settings from forum group.

## Changes made
- changed to use common URL logic

## How did you test these updates?  

Tested multiple forums and pages in test copy of dnncommunity.org

## PR Template Checklist

- [X] Fixes Bug
- [ ] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #425

### CODE REVIEW

**Comment by WillStrohl** [comment]
@johnhenley So, I think we have no choice but to put this into 8.0, right?  At least, we shouldn't try another 7.xx.  That would mess us up again a bit.

**Review by WillStrohl — APPROVED** [review]
Looks like such an elegant fix!  :)

**Comment by johnhenley** [comment]
We could branch from master to create a separate branch for 7.0.13 if you want. That’s what I did for testing this.

John
________________________________

**Comment by WillStrohl** [comment]
I'm afraid we might step on our own toes.  😆

**Comment by WillStrohl** [comment]
We're so close to an RC, I think it makes best sense to get 8.0 released.  This issue is a bit limited in scope and can be out there for a bit for sites that have run into it.

**Pull request merged**
