### PR TITLE
Move control panel out of main folder into subfolder 

### LINKED ISSUE #179: Move Forums Control Panel to a subfolder
## Please summarize your question in one sentence
Remove hard-coded null checks for database columns by ordinal number and use better null checking

## Give a more extended description
Declutter main Forums folder by moving control panel pages code to a subfolder. This will make it easier for future maintenance.

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Move control panel out of main folder into subfolder 
## Changes made
- move control panel out of main folder and into subfolder
- move jquery-ui*css to controlpanel folder

## PR Template Checklist

- [ ] Fixes Bug
- [ ] Feature solution
- [X] Other

## Please mark which issue is solved

Close #179

### CODE REVIEW

**Comment by WillStrohl** [comment]
@johnhenley @Timo-Breumelhof This PR moves the control panel CSS to a new folder and then makes it no longer use the CSS from the forum theme. I know we're splitting the CSS up to be better structured.  However, in this case, the change is 100% a breaking change for anyone with significant theme updates.  

Keeping that in mind...  Should we wait to merge this until version 8.0?

**Comment by johnhenley** [comment]
> @johnhenley @Timo-Breumelhof This PR moves the control panel CSS to a new folder and then makes it no longer use the CSS from the forum theme. I know we're splitting the CSS up to be better structured.  However, in this case, the change is 100% a breaking change for anyone with significant theme updates.  
> 
> 
> 
> Keeping that in mind...  Should we wait to merge this until version 8.0?  

I didn't see this as a breaking change as this css was only used by the control panel which is why i separated it from themes.

**Comment by Timo-Breumelhof** [comment]
As long as the CSS is only moved to another file and the load order is the same, I don;t see this as a breaking change either TBH.

**Comment by johnhenley** [comment]
@WillStrohl just approve it :)

**Comment by johnhenley** [comment]
Cancelling this one since it's sat too long and doesn't have enough value added.

**Pull request closed without merging**
