### PR TITLE
Fix typo in sproc activeforums_Attachments_Get

### LINKED ISSUE #59: Active Forums Crashes When Clicking to View Image
## Describe the bug
When i click on an image i have uploaded to a forum topic, active forums crashes with a message stating that a critical error has occurred.

## Software Versions
- DNN: 9.8.1
- Module: 6.5

## To Reproduce
1. Navigate to active forums forum
2. Click on New New Topic
3. Upload an Image (attachment)
4. Click the image icon/link in the topic
5. Second tab of browser opens with error message noted above

## Expected behavior
I expect the image to render without any error. My image was not rendered because of the sql error reported in the log

## Error log
**Note: Debug DLL's**
AbsoluteURL:/DesktopModules/ActiveForums/viewer.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:810ad2c6-d9bf-41c2-8afc-5900d4c2d80a

AssemblyVersion:9.8.1

PortalId:0

UserId:1

TabId:22

RawUrl:/DesktopModules/ActiveForums/viewer.aspx?portalid=0&moduleid=409&attachmentid=1

Referrer:https://www.etiquemarket.com/forums/aft/1

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

ExceptionHash:/VFfOZMMg9MveQQqJsZTO0DUn/8=

Message:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

StackTrace:

InnerMessage:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

InnerStackTrace:

at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(SqlConnection connection, SqlTransaction transaction, CommandType commandType, String commandText, SqlParameter[] commandParameters, SqlConnectionOwnership connectionOwnership)
at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, String spName, Object[] parameterValues)
at DotNetNuke.Modules.ActiveForums.Data.AttachController.Get(Int32 attachmentId, Int32 fileId, Boolean withSecurity)
at DotNetNuke.Modules.ActiveForums.af_viewer.OnLoad(EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:
 0

### PR DESCRIPTION
**Pull request by johnhenley**
## Changes made
- Create 07.00.00.SqlDataProvider 
- missing right bracket on line 20.

## PR Template Checklist

- [x] Fixes Bug
- [ ] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #59

### CODE REVIEW

**Comment by Timo-Breumelhof** [comment]
Great thanks :-)

**Comment by johnhenley** [comment]
> fixes #59

Also fixes #106

**Comment by johnhenley** [comment]
@Timo-Breumelhof I know I'm probably driving you crazy, but I had two questions:
- I was wondering if this new release really deserves 07.00.00 or should it be 06.07.00?
- should I also include the version changes for all the other files like manifests? Or do you do that?

**Comment by Timo-Breumelhof** [comment]
@johnhenley 
No you are not driving me crazy, github is confusing to start with, once you understand the basics you'll be fine.
If you need more help ping me.
We decided to make it v 07.00.00 because I fixed HTML errors in templates and it might influence exiting users (it's a bit of a heads-up).
No need to change manifest files etc., the person doing the release handles that (mostly @WillStrohl ).

**Comment by johnhenley** [comment]
@Timo-Breumelhof  hopefully i've cleaned up my mess...

**Comment by johnhenley** [comment]
I fiddled a lot with branches today and think I get it know. Once I realized you could branch from a specific commit vs a whole branch, that was an aha moment! Thanks for your help and support!!

John
________________________________

**Pull request closed without merging**
