### PR TITLE
TASK: Remove not used themes/module.css 

### LINKED ISSUE #552: TASK: Remove themes/module.css from install
This file is an artifact from previous releases, and is not used. Remove it during upgrades.

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
themes/module.css not used in v7; remove from existing installations during upgrade.

## Changes made
- add to 08.00.00.txt to remove file during upgrade

## How did you test these updates?  
Local install upgrade from 07.00.12

## PR Template Checklist

- [ ] Fixes Bug
- [ ] Feature solution
- [X] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #552

### CODE REVIEW

**Review by WillStrohl — APPROVED** [review]
Oh wow... I didn't know wild cards were possible in a cleanup file. Nice!

**Comment by johnhenley** [comment]
> Oh wow... I didn't know wild cards were possible in a cleanup file. Nice! 

Honestly I'm not sure it does :( I will need to test and see if it actually removes those files.

**Comment by johnhenley** [comment]
> Oh wow... I didn't know wild cards were possible in a cleanup file. Nice!

@WillStrohl no it doesn't work :(

**Comment by WillStrohl** [comment]
Are there any errors, or does it appear to simply ignore the files listed in the manifest?  🤔

**Comment by johnhenley** [comment]
> Are there any errors, or does it appear to simply ignore the files listed in the manifest? 🤔

It just ignores.

**Comment by WillStrohl** [comment]
@valadas Did you know this? 🤔

**Comment by valadas** [comment]
I rarely use cleanup files, so I don't really know or tested... For module assets I usually use a glob pattern in the manifest and delete all and replace with a new resource.zip file... This ensures I always wipe everything and have fresh assets for the current version. Now if anything else plays with the module assets then that would not work so your mileage might vary if this is the case here...

**Comment by johnhenley** [comment]
@WillStrohl do you think we should use the manifest vs cleanup files? I just went along with what was there when I came along.

**Comment by WillStrohl** [comment]
@johnhenley The update is already there and will work.  There's no need to, unless **you** want to switch it.  I'll go with whichever decision you make. 😉

**Pull request merged**
