### PR TITLE
Change email API usage to use Portal-Specific SMTP configuration

### LINKED ISSUE #96: Email Sending Error: Portal Specific SMTP setting ignored
## Please summarize your question in one sentence

Emails from Active Forum are not sending using the portal specific SMTP configurations

## Give a more extended description
I discovered that emails sent via Active Forum are not using the portal specific SMTP configuration. 

The emails were working fine in the past, but stopped recently. After investigation I found that the reason they stopped working is the host SMTP server configuration was not longer configured correctly to send out emails. This issue is not related to a recent upgrade to DNN 9.9.1.

DNN 9.9.1 install with version 6.6.0 of Active Forums installed.

## Steps to reproduce (if needed)

Using the tip from Timo-Breumelhof I setup the installation to store eml files in a local server pickup folder. I configured the portal SMTP to use the localhost configuration. Emails were not sent to the pickup folder. When I configured the host SMTP server with the same configuration, the emails were saved into the pickup folder. 

This is an indication that active forum is not looking at the portal SMTP server settings if they are configured.

### PR DESCRIPTION
**Pull request by johnhenley**
## Changes made
- add PortalID column to activeforums_Queue table
- update activeforums_Queue_Add/activeforums_Queue_List to include PortalID
- update email-related code to include portalId
- update email-related code to retrieve portal-specific SMTP configuration, and if used, override host SMTP configuration
- update DNN email API call to one that allows passing SMTP configuration parameters

## PR Template Checklist

- [X] Fixes Bug
- [ ] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #96

### CODE REVIEW

**Comment by WillStrohl** [comment]
Did you intend to close this PR before it gets merged?

**Comment by johnhenley** [comment]
reopened

**Comment by johnhenley** [comment]
@WillStrohl  since I have multiple sql updates across the issues/pull requests, I added a comment at the start/end of the sql 
Let me know if that helps, or if you'd rather I do them in a particular order?

**Comment by WillStrohl** [comment]
@johnhenley  This is great!  

One thing to note after reviewing this PR is that there are public method signatures that are changed, but in a way that's not backwards compatible.  For example, the current ones could retain the changes you've made, but another new one should be created that matches the original signature, but then gathers the `PortalID` from the current `PortalSettings` object, then pass everything through to the updated one that expects the `PortalID.`  

While it's a small chance that anyone is using these methods for custom development, it's not uncommon and we should try to prevent a breaking change, if we can.  

Please let me know your thoughts at your convenience.  

As always, thank you for a great contribution!

**Comment by johnhenley** [comment]
> @johnhenley This is great!
> 
> One thing to note after reviewing this PR is that there are public method signatures that are changed, but in a way that's not backwards compatible. For example, the current ones could retain the changes you've made, but another new one should be created that matches the original signature, but then gathers the `PortalID` from the current `PortalSettings` object, then pass everything through to the updated one that expects the `PortalID.`
> 
> While it's a small chance that anyone is using these methods for custom development, it's not uncommon and we should try to prevent a breaking change, if we can.
> 
> Please let me know your thoughts at your convenience.
> 
> As always, thank you for a great contribution!

@WillStrohl Understood.

**Comment by johnhenley** [comment]
> > @johnhenley This is great!
> > One thing to note after reviewing this PR is that there are public method signatures that are changed, but in a way that's not backwards compatible. For example, the current ones could retain the changes you've made, but another new one should be created that matches the original signature, but then gathers the `PortalID` from the current `PortalSettings` object, then pass everything through to the updated one that expects the `PortalID.`
> > While it's a small chance that anyone is using these methods for custom development, it's not uncommon and we should try to prevent a breaking change, if we can.
> > Please let me know your thoughts at your convenience.
> > As always, thank you for a great contribution!
> 
> @WillStrohl Understood.

@WillStrohl  But...is it OK to remove protected methods that have 0 references ?

**Comment by WillStrohl** [comment]
Yes. Private and protected methods wouldn't be directly used by any integrations.  If someone managed to find a way to do that somehow, we wouldn't need to worry about it anyway.  Only public methods are at risk.  :)

**Comment by johnhenley** [comment]
@WillStrohl  I did a few updates to restore the public methods that I had removed.

**Pull request merged**
