### PR TITLE
Bootstrap Theme collapse fix + quickreply alignment

### LINKED ISSUE #788: BUG: BTST Theme Forum Collapse not working in BTST5
## Describe the bug
The collapse Forum and Quick reply does not work in a Bootstrap5 Theme, it does in v 4

## Software Versions
- DNN: 09.13.00
- Module: 08.00.01

## To Reproduce
1. Use the Forum with the new Bootstrap Them in combination with a Bootstrap 5 DNN Theme
2. Try the collapse icons
3. They don't work

## Expected behavior
Collapse should work

### LINKED ISSUE #789: BUG: BTST Theme Quick Reply layout and alignment
## Is your feature request related to a problem?
- TextArea is too wide
- Alignment of text next to checkbox
- 
image

## Describe the solution you'd like
fix this :-)

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**
Fixes the collapse icons for Bootstrap 5 

## Changes made
- Added some attributes to the collapse elements to support Bootstrap 5
- Fix quick reply alignment

## How did you test these updates?  

Local install

## PR Template Checklist

- [x] Fixes Bug
- [ ] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #788 
Close #789

### CODE REVIEW

**Comment by Timo-Breumelhof** [comment]
@johnhenley I made a small "mistake" this mow fixes 2 issues :-)

**Review by johnhenley — CHANGES_REQUESTED** [review]
@Timo-Breumelhof the quick reply is OK. However, the group collapse is collapsing all groups, not just the one group (I'm guessing you aren't testing with multiple groups?). I remember we talked about adding a token so you could have a target for the group being collapsed? See this screenshot from an email exchange we had to discuss using the [FORUMGROUPID] token in the href of the collapse.

`” href-“#group[FORUMGROUPID]”>`

**Comment by Timo-Breumelhof** [comment]
@johnhenley hmm, I didn't notice that. I'll have a look

**Comment by Timo-Breumelhof** [comment]
@johnhenley 
I now implemented it but the token does not seem to work inside the [GROUP]..

See:
image

**Comment by johnhenley** [comment]
Just put it in the href for the collapse. Don’t change the group

John
________________________________

**Comment by Timo-Breumelhof** [comment]
@johnhenley with your #795 PR this should be working now, right?

**Comment by Timo-Breumelhof** [comment]
@johnhenley I'm merging so we can test and fix whatever's left

**Pull request merged**
