### PR TITLE
Modulesettings input widths fixes #317

### LINKED ISSUE #317: Input for Avatar width size issue
## Describe the bug
The input to set the width of the Avatar is too small

## Software Versions
- DNN: 09.11.02
- Module: 07.00.03

## To Reproduce
1. Open Module settings > Active Forums Settings > Community Options
2. See the inputs for Avatar

## Screenshots
image

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**
## Changes made
- Made inputs wider so the content does not get "cropped"

## PR Template Checklist

- [ ] Fixes Bug
- [x] Feature solution
- [ ] Other

## Please mark which issue is solved

Fixes #317 

Close #317

### CODE REVIEW

**Comment by Timo-Breumelhof** [comment]
@johnhenley @WillStrohl This is a temporary fix, I just used what the module uses right now, the width attribute of the .NET control.
We should (in the future) use CSS from Module.css for this IMO as you can then use width: 3rem, which scales much better :-).

**Comment by johnhenley** [comment]
@Timo-Breumelhof Can you also enlarge the flood interval? I changed that from a drop-down to an input box but noticed it also crops off when larger integers like 200 are entered. 

Is there an overall DNN styling standard for module settings that should be used?

**Comment by WillStrohl** [comment]
We should be re-using what DNN comes with as much as we can, so we don't have to rely on and maintain these kinds of workarounds long-term.

**Review by WillStrohl — APPROVED** [review]
Looks good

**Pull request merged**
