### PR TITLE
Remove (obsolete/legacy) Active Social integration

### LINKED ISSUE #173: Remove legacy ActiveSocial integration
DNN Community Forums became part of the DNN ecosystem when Active Modules was acquired by DNN several years ago. At the time, it was called ActiveForums and was licensed by Active Modules along with a companion product, ActiveSocial. After the acquisition, the social components (groups, journals, etc.) were implemented within the DNN platform.

The forums code based was converted from VB to C#, and forked several times before being adopted and folded into the DNN Community and renamed to DNN Community Forums. 

However, there is still a lot of legacy code that exists to support integration with the long-abandoned ActiveSocial. In fact, every time you visit a page containing the Forums module, code checks to see if you have ActiveSocial installed by looking for a DLL. 

Any site with ActiveSocial should have been converted by now to use the social features within DNN platform and no longer should be using an abandoned and unsupported product. 

This issue is a placeholder for removing integration with ActiveSocial.

### PR DESCRIPTION
**Pull request by johnhenley**
### Description of PR...
Remove (obsolete) Active Social integration

## PR Template Checklist

- [ ] Fixes Bug
- [ ] Feature solution
- [X] Other

## Please mark which issue is solved

Close #173

### CODE REVIEW

**Comment by johnhenley** [comment]
@WillStrohl I made the "release 07.00.04" since it includes a minor SQL update to remove any active social settings. Once you accept this and the other outstanding pull requests, you should have minor releases for 07.00.01 (already released) and 07.00.02, 07.00.03, and 07.00.04. None of those new ones actually need to be released, but the next pull request for issue #93 will be version 08.00.00, and will include references to all of these releases in the upgrade string and SQL files. 

So PLEASE approve them in order by PR #.

**Comment by WillStrohl** [comment]
Thank you for helping to track that, @johnhenley.  FYI, @Timo-Breumelhof too.  :)

**Comment by WillStrohl** [comment]
There appear to be identical in this PR that are also in PR #194 and in another one previously too.  How are you putting these PRs together?  I want to be sure none of us are doing more work than we need to be doing.  :)

**Comment by johnhenley** [comment]
PLEASE approve them in order by PR #.
#171 
#180 
#181 
#188 
#190 
#192 
#193
#194 


#194 is the big one, and it does depend on some of the prior ones being there. 
You will save a lot of headaches if you do them in order :)

**Pull request merged**
